import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Match, Team, Player, PlayerStats, MatchLogEntry } from '@/types'

interface ReportData {
  match: Match
  teamA: Team
  teamB: Team
  teamAPlayerStats: { player: Player; stats: PlayerStats }[]
  teamBPlayerStats: { player: Player; stats: PlayerStats }[]
  matchLogs: MatchLogEntry[]
  playerOfGame: { player: Player; team: Team; score: number } | null
}

// Format date for display
const formatDate = (dateStr: string): string => {
  const date = new Date(dateStr)
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

// Generate the PDF report
export function generateMatchReport(data: ReportData): void {
  const { match, teamA, teamB, teamAPlayerStats, teamBPlayerStats, playerOfGame } = data

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Title
  doc.setFontSize(24)
  doc.setTextColor(40, 40, 40)
  doc.text('SideOut', pageWidth / 2, 20, { align: 'center' })
  
  doc.setFontSize(16)
  doc.text('Match Report', pageWidth / 2, 30, { align: 'center' })

  // Match Info
  doc.setFontSize(12)
  doc.setTextColor(80, 80, 80)
  doc.text(formatDate(match.match_date || match.created_at), pageWidth / 2, 40, { align: 'center' })

  // Teams and Score
  doc.setFontSize(20)
  doc.setTextColor(0, 0, 0)
  
  const teamAName = teamA?.name || 'Team A'
  const teamBName = teamB?.name || 'Team B'
  
  doc.text(teamAName, 40, 55)
  doc.text(match.team_a_score.toString(), 70, 55)
  doc.text('-', 80, 55)
  doc.text(match.team_b_score.toString(), 90, 55)
  doc.text(teamBName, 110, 55)

  // Match Status
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  const statusText = match.status === 'completed' ? 'Completed' : 'In Progress'
  doc.text(`Status: ${statusText}`, pageWidth / 2, 65, { align: 'center' })
  doc.text(`Sets: ${match.current_set}/5`, pageWidth / 2, 72, { align: 'center' })

  // Team A Player Stats
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text(`${teamAName} - Player Statistics`, 14, 85)

  const teamAStatsData = teamAPlayerStats.map(({ player, stats }) => [
    `#${player.jersey_number}`,
    player.name,
    player.position,
    stats.kills.toString(),
    stats.errors.toString(),
    stats.attacks.toString(),
    stats.blocks.toString(),
    stats.aces.toString(),
    stats.perfect_receptions.toString(),
    stats.good_receptions.toString(),
  ])

  autoTable(doc, {
    startY: 90,
    head: [['#', 'Name', 'Pos', 'Kills', 'Err', 'Att', 'Blk', 'Aces', 'Perfect', 'Good']],
    body: teamAStatsData,
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
  })

  // Team B Player Stats
  const teamBStatsData = teamBPlayerStats.map(({ player, stats }) => [
    `#${player.jersey_number}`,
    player.name,
    player.position,
    stats.kills.toString(),
    stats.errors.toString(),
    stats.attacks.toString(),
    stats.blocks.toString(),
    stats.aces.toString(),
    stats.perfect_receptions.toString(),
    stats.good_receptions.toString(),
  ])

  autoTable(doc, {
    startY: (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15,
    head: [['#', 'Name', 'Pos', 'Kills', 'Err', 'Att', 'Blk', 'Aces', 'Perfect', 'Good']],
    body: teamBStatsData,
    theme: 'striped',
    headStyles: { fillColor: [239, 68, 68] },
  })

  // Player of the Game
  if (playerOfGame) {
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('Player of the Game', 14, (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 25)
    
    doc.setFontSize(12)
    doc.text(
      `${playerOfGame.player.name} (${playerOfGame.team.name}) - Score: ${playerOfGame.score.toFixed(2)}`,
      14,
      (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 35
    )
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(
    `Generated by SideOut Volleyball Analytics on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  )

  // Save the PDF
  const fileName = `SideOut_Match_${teamAName}_vs_${teamBName}_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(fileName)
}

// Export match logs to CSV
export function exportMatchLogsToCSV(logs: MatchLogEntry[], teamA: Team, teamB: Team): void {
  const headers = ['Timestamp', 'Team', 'Player', 'Action', 'Position']
  
  const rows = logs.map(log => {
    const team = log.team_id === teamA?.id ? teamA.name : teamB.name
    return [
      new Date(log.timestamp).toLocaleString(),
      team,
      log.player?.name || 'Unknown',
      log.action_type,
      log.position?.toString() || '',
    ]
  })

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
  ].join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const fileName = `SideOut_Match_Log_${new Date().toISOString().split('T')[0]}.csv`
  
  link.href = URL.createObjectURL(blob)
  link.download = fileName
  link.click()
}

// Calculate hitting percentage
export function calculateHittingPercentage(kills: number, errors: number, attempts: number): number {
  if (attempts === 0) return 0
  return ((kills - errors) / attempts) * 100
}

// Calculate reception efficiency
export function calculateReceptionEfficiency(perfect: number, good: number, errors: number, total: number): number {
  if (total === 0) return 0
  return (((perfect + good) - errors) / total) * 100
}

// Calculate performance score
export function calculatePerformanceScore(stats: PlayerStats): number {
  return (
    (stats.kills * 1.0) +
    (stats.blocks * 1.5) +
    (stats.solo_blocks * 1.5) +
    (stats.block_assists * 1.0) +
    (stats.aces * 1.2) +
    (stats.assists * 0.5) +
    (stats.excellent_sets * 0.5) +
    (stats.excellent_digs * 1.0) -
    stats.errors -
    stats.service_errors -
    stats.reception_errors -
    stats.dig_errors
  )
}
